CATEGORY_NAME_MAX_LEN = 256
CONFIRMATION_CODE_MAX_LEN = 100
EMAIL_MAX_LEN = 254
FIRST_LETTERS_AMOUNT = 20
GENRE_NAME_MAX_LEN = 256
MAX_SCORE = 10
MIN_SCORE = 1
ROLE_MAX_LEN = 10
TEXT_PREVIEW_LEN = 20
TITLE_NAME_MAX_LEN = 256
USERNAME_MAX_LEN = 150
USER = 'user'
ADMIN = 'admin'
MODERATOR = 'moderator'
ROLE_CHOICES = (
    (USER, 'User'),
    (MODERATOR, 'Moderator'),
    (ADMIN, 'Admin'),
)
