# Generated by Django 3.2 on 2024-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20240718_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
